name: 'Terraform Build'

#Build can only be ran manually or on PR to main
on:
  push:
    branches:
    - main
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform CI'
    runs-on: ubuntu-latest
    environment: mvp
    env:
      PIPELINE_PLAN: "pipeline.plan"
      TERRAFORM_PATH: "dns/custom-sites"
      SHORTHAND_PROJECT_NAME: "ctdo"
      SHORTHAND_ENVIRONMENT: "mvp"
      SHORTHAND_LOCATION: "uks"
      TERRAFORM_COMPLIANCE_POLICY: "https://github.com/craigthackerx/azure-terraform-compliance-naming-convention.git//?ref=main"


    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: hashicorp/setup-terraform@v1.2.1
      - uses: actions/checkout@v2

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init & Plan
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: |

          rm -rf .terraform && \
          mkdir -p .terraform && \

          terraform init \
          -backend-config="storage_account_name=${TF_VAR_AZURE_BACKEND_SA_NAME}" \
          -backend-config="access_key=${TF_VAR_AZURE_BACKEND_SA_KEY}" \
          -backend-config="container_name=${TF_VAR_AZURE_BACKEND_SA_CONTAINER_NAME}" \
          -backend-config="key=${TF_VAR_short}-${TF_VAR_env}.terraform.tfstate" && \

          printf '%s' "${TF_VAR_env}" > .terraform/environment && \

          terraform workspace select "${TF_VAR_env}" || terraform workspace new "${TF_VAR_env}"

          terraform plan -out ${PIPELINE_PLAN} && \

          terraform validate

        env:
          TF_VAR_short: ${{ env.SHORTHAND_PROJECT_NAME }}
          TF_VAR_env: ${{ env.SHORTHAND_ENVIRONMENT }}
          TF_VAR_loc: ${{ env.SHORTHAND_LOCATION }}

          TF_VAR_AZURE_BACKEND_SA_NAME: ${{ secrets.TF_VAR_AZURE_BACKEND_SA_NAME }}
          TF_VAR_AZURE_BACKEND_SA_KEY: ${{ secrets.TF_VAR_AZURE_BACKEND_SA_KEY}}
          TF_VAR_AZURE_BACKEND_SA_CONTAINER_NAME: ${{ secrets.TF_VAR_AZURE_BACKEND_SA_CONTAINER_NAME }}

          TF_VAR_DO_TOKEN: ${{ secrets.TF_VAR_DO_TOKEN }}

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12.641.0
        with:
          directory: ${{ env.TERRAFORM_PATH }}
          skip_check:

      - name: terraform-compliance
        uses: terraform-compliance/github_action@0.3.0
        with:
          plan: ${{ env.TERRAFORM_PATH}}/${{ env.PIPELINE_PLAN}}
          features: ${{ env.TERRAFORM_COMPLIANCE_POLICY}}


      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: |
          terraform apply -auto-approve ${PIPELINE_PLAN}
        env:
          TF_VAR_short: ${{ env.SHORTHAND_PROJECT_NAME }}
          TF_VAR_env: ${{ env.SHORTHAND_ENVIRONMENT }}
          TF_VAR_loc: ${{ env.SHORTHAND_LOCATION }}
